version: '3.8'
services:

  db:
    build:
      context: .
      dockerfile: db/Dockerfile
    image: 'db'
    container_name: db
    environment:
       ACCEPT_EULA: "Y"
       SA_PASSWORD: "Un!q@to2023"
    restart: always
    networks:
      example:
        ipv4_address: 172.226.0.101

    volumes:
        - mssql-data:/var/opt/mssql


  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    image: 'api'
    container_name: api
    restart: always
    networks:
      example:
        ipv4_address: 172.226.0.102
    depends_on:
      - db
    ports:
      - 127.0.0.1:4567:80 #Only accessible from localhost, if you want to connect to "api" container from remote please delete the localhost ip address, "127.0.0.1"


volumes:
  mssql-data:

networks:
  example:
    name: example
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.226.0.0/24
