version: '3.7'
services:

  vero-db-mssql:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vero-db-mssql
    ports:
        - '127.0.0.1:1433:1433' #Only accessible from localhost
    environment:
       ACCEPT_EULA: "Y"
       SA_PASSWORD: "Un!q@to2023"
    restart: always
    networks:
      vero:
        ipv4_address: 172.226.0.101

    volumes:
        - mssql-data:/var/opt/mssql




volumes:
  mssql-data:

networks:
  vero:
    name: vero
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.226.0.0/24
